export { HeroSection } from './HeroSection';
export { InsiderSection } from './InsiderSection';
export { SequenceSection } from './SequenceSection';
export { BenefitsSection } from './BenefitsSection';
export { ReviewsSection } from './ReviewsSection';
export { TestimonialsSection } from './TestimonialsSection';
export { FlavourSection } from './FlavourSection';
export { PaymentSection } from './PaymentSection';
export { Footer } from './Footer';
